apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_NAME: "mydatabase_1"
  DB_USER: "myuser_1"
  DB_HOST: "myhost_1"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  eHh4eXl5enp6