apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_NAME: db_1
  DB_USERNAME: postgres_user_1
  DB_HOST: postgres_host_1
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_SECRET: eHh4eXl5enp6OTk5